-- db/migrations/002_poker.sql
-- Poker trainer persistence (spec §6.2, contracts §4).
-- Chip amounts are integer units: 1 unit = 0.5 BB (the table plays sb = 1, bb = 2).
-- Expected values (all-in EV, EV loss) are fractional units.

CREATE TABLE poker_sessions (
  id            uuid PRIMARY KEY,                                  -- generated by the client
  bot_version   text NOT NULL,
  table_mode    text NOT NULL CHECK (table_mode IN ('random', 'custom')),
  lineup        jsonb NOT NULL,                                    -- [{seat, personaId}] bot seats at sit-down
  hero_seat     int NOT NULL CHECK (hero_seat BETWEEN 0 AND 5),
  started_at    timestamptz NOT NULL,
  ended_at      timestamptz,                                       -- NULL while open
  hands         int NOT NULL DEFAULT 0,                            -- kept current by POST hands
  net           int NOT NULL DEFAULT 0,                            -- units, kept current by POST hands
  allin_adj_net numeric(12,2) NOT NULL DEFAULT 0,                  -- units, net with all-in luck removed
  rebuys        int NOT NULL DEFAULT 0,                            -- computed when the session closes
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX poker_sessions_started ON poker_sessions (started_at DESC);
CREATE INDEX poker_sessions_open ON poker_sessions (started_at) WHERE ended_at IS NULL;

CREATE TABLE poker_hands (
  id               uuid PRIMARY KEY,
  session_id       uuid NOT NULL REFERENCES poker_sessions (id) ON DELETE CASCADE,
  hand_no          int NOT NULL CHECK (hand_no >= 1),
  played_at        timestamptz NOT NULL,                           -- hand start
  button_seat      int NOT NULL CHECK (button_seat BETWEEN 0 AND 5),
  hero_seat        int NOT NULL CHECK (hero_seat BETWEEN 0 AND 5),
  hero_start_stack int NOT NULL CHECK (hero_start_stack > 0),      -- units; detects rebuys
  hero_actions     int NOT NULL CHECK (hero_actions >= 0),         -- hero act events; bounds the profile window
  lineup           jsonb NOT NULL,                                 -- [{seat, personaId}] bot seats this hand
  hole_cards       jsonb NOT NULL,                                 -- [{seat, cards: 'AhKs'}] every seat
  board            text NOT NULL,                                  -- e.g. 'AhKs9dTc2h' (may be shorter)
  events           jsonb NOT NULL,                                 -- the full engine event log
  pot              int NOT NULL CHECK (pot >= 0),                  -- units
  hero_net         int NOT NULL,                                   -- units
  hero_allin_ev    numeric(10,2),                                  -- units; NULL unless graded (Phase 5)
  showdown         boolean NOT NULL,
  UNIQUE (session_id, hand_no)
);

CREATE INDEX poker_hands_recent ON poker_hands (played_at DESC, id DESC);

CREATE TABLE poker_decisions (
  hand_id          uuid NOT NULL REFERENCES poker_hands (id) ON DELETE CASCADE,
  idx              int NOT NULL,                                   -- index into the hand's events
  street           text NOT NULL CHECK (street IN ('preflop', 'flop', 'turn', 'river')),
  position         text NOT NULL CHECK (position IN ('UTG', 'HJ', 'CO', 'BTN', 'SB', 'BB')),
  spot             text NOT NULL,                                  -- e.g. 'pf.open', 'river.facing_bet.oop'
  action           text NOT NULL CHECK (action IN ('fold', 'check', 'call', 'bet', 'raise')),
  size             int,                                            -- units, raise-to; NULL for fold/check/call
  pot              int NOT NULL,                                   -- units, before the decision
  to_call          int NOT NULL,                                   -- units
  equity           real,                                           -- NULL preflop
  needed_equity    real,                                           -- NULL when nothing to call
  recommended      jsonb NOT NULL,                                 -- {action, size, evByOption}
  ev_loss          real NOT NULL CHECK (ev_loss >= 0),             -- units
  grade            text NOT NULL CHECK (grade IN ('good', 'inaccuracy', 'mistake', 'blunder')),
  confident        boolean NOT NULL,
  analysis_version int NOT NULL,
  PRIMARY KEY (hand_id, idx)
);

CREATE INDEX poker_decisions_spot ON poker_decisions (spot);
