// Preflop chart lookup. Charts are generated by scripts/poker/gen-preflop.js into data/preflop/charts-v1.json.
import data from '../data/preflop/charts-v1.json' with { type: 'json' };
import { CLASS_COUNT, combosIn, kindOf } from './handClass.js';

export const CHART_VERSION = data.version;

/** Classes strongest first. */
export const STRENGTH_ORDER = Object.freeze(data.order.slice());

/** RANK_PCT[cls] = share of combos stronger than the middle of `cls` (0 = strongest). */
export const RANK_PCT = new Float64Array(CLASS_COUNT);
{
  let before = 0;
  for (const cls of STRENGTH_ORDER) {
    RANK_PCT[cls] = (before + combosIn(cls) / 2) / 1326;
    before += combosIn(cls);
  }
}

// Classes of one kind (pair/suited/offsuit) sorted strongest first, for width scaling.
const BY_KIND = { pair: [], suited: [], offsuit: [] };
for (const cls of STRENGTH_ORDER) BY_KIND[kindOf(cls)].push(cls);

const digit = (ch) => (ch === 'X' ? 1 : Number(ch) / 10);

export const hasChart = (key) => Object.hasOwn(data.charts, key);

export const chartKeys = () => Object.keys(data.charts);

/** @returns {{ raise:number, call:number }} base frequencies in [0, 1]; fold = 1 - raise - call */
export function chartFreqs(key, cls) {
  const chart = data.charts[key];
  if (!chart) throw new Error(`Unknown chart: ${key}`);
  return { raise: digit(chart.raise[cls]), call: digit(chart.call[cls]) };
}

// The class of the same kind whose strength percentile is closest to `pct`.
function nearestOfKind(cls, pct) {
  const list = BY_KIND[kindOf(cls)];
  let best = list[0];
  for (const other of list) {
    if (Math.abs(RANK_PCT[other] - pct) < Math.abs(RANK_PCT[best] - pct)) best = other;
  }
  return best;
}

/**
 * Chart frequencies with the raise and call ranges widened (mul > 1) or tightened (mul < 1).
 * A hand at strength percentile p plays like the hand of the same kind at p / mul.
 */
export function scaledFreqs(key, cls, raiseMul = 1, callMul = 1) {
  const raiseFrom = raiseMul === 1 ? cls : nearestOfKind(cls, RANK_PCT[cls] / raiseMul);
  const callFrom = callMul === 1 ? cls : nearestOfKind(cls, RANK_PCT[cls] / callMul);
  const raise = chartFreqs(key, raiseFrom).raise;
  const call = Math.min(chartFreqs(key, callFrom).call, 1 - raise);
  return { raise, call };
}

/** 169 class weights: 1 for the strongest `share` of combos, 0 otherwise. */
export function topShareWeights(share) {
  const out = new Float32Array(CLASS_COUNT);
  for (let cls = 0; cls < CLASS_COUNT; cls += 1) out[cls] = RANK_PCT[cls] <= share ? 1 : 0;
  return out;
}
