// Cached heads-up preflop equities (class vs class), generated by scripts/poker/gen-preflop.js.
import data from '../data/preflop/equity169.json' with { type: 'json' };
import { CLASS_COUNT, combosIn } from './handClass.js';

/** Decodes base64 little-endian Uint16 values into equities in [0, 1]. */
export function decodeEquityTable(base64) {
  const binary = atob(base64);
  const out = new Float32Array(binary.length / 2);
  for (let i = 0; i < out.length; i += 1) {
    out[i] = (binary.charCodeAt(2 * i) | (binary.charCodeAt(2 * i + 1) << 8)) / 65535;
  }
  return out;
}

const TABLE = decodeEquityTable(data.table);

/** Heads-up all-in equity of class `a` against class `b`. */
export const classEquity = (a, b) => TABLE[a * CLASS_COUNT + b];

/**
 * Equity of class `cls` against a range given as 169 class weights (each class also weighted by its combo count).
 * Card removal is ignored. Returns 0.5 for an empty range.
 */
export function equityVsClassWeights(cls, weights) {
  let num = 0;
  let den = 0;
  for (let b = 0; b < CLASS_COUNT; b += 1) {
    const w = weights[b] * combosIn(b);
    if (w <= 0) continue;
    num += w * TABLE[cls * CLASS_COUNT + b];
    den += w;
  }
  return den > 0 ? num / den : 0.5;
}

/** Equity of every class against a uniformly random hand. */
export const EQUITY_VS_ANY = Float32Array.from({ length: CLASS_COUNT }, (_, cls) =>
  equityVsClassWeights(cls, new Float32Array(CLASS_COUNT).fill(1)),
);
